In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("WHO-COVID-19-global-data.csv")
df

,DateReported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
0,2020-01-03,AF,Afghanistan,EMRO,0,0,0,0
1,2020-01-04,AF,Afghanistan,EMRO,0,0,0,0
2,2020-01-05,AF,Afghanistan,EMRO,0,0,0,0
3,2020-01-06,AF,Afghanistan,EMRO,0,0,0,0
4,2020-01-07,AF,Afghanistan,EMRO,0,0,0,0
...,...,...,...,...,...,...,...,...
121227,2021-05-23,ZW,Zimbabwe,AFRO,15,38679,0,1586
121228,2021-05-24,ZW,Zimbabwe,AFRO,3,38682,0,1586
121229,2021-05-25,ZW,Zimbabwe,AFRO,14,38696,0,1586
121230,2021-05-26,ZW,Zimbabwe,AFRO,10,38706,1,1587
121231,2021-05-27,ZW,Zimbabwe,AFRO,113,38819,2,1589

In [11]:
df["DateReported"] = pd.to_datetime(df["DateReported"])
data = df.groupby("DateReported").sum()
data

,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
DateReported,,,,,,,
2020-01-03,AFALDZASADAOAIAGARAMAWAUATAZBSBHBDBBBYBEBZBJBM...,AfghanistanAlbaniaAlgeriaAmerican SamoaAndorra...,EMROEUROAFROWPROEUROAFROAMROAMROAMROEUROAMROWP...,0,0,0,0
2020-01-04,AFALDZASADAOAIAGARAMAWAUATAZBSBHBDBBBYBEBZBJBM...,AfghanistanAlbaniaAlgeriaAmerican SamoaAndorra...,EMROEUROAFROWPROEUROAFROAMROAMROAMROEUROAMROWP...,1,1,0,0
2020-01-05,AFALDZASADAOAIAGARAMAWAUATAZBSBHBDBBBYBEBZBJBM...,AfghanistanAlbaniaAlgeriaAmerican SamoaAndorra...,EMROEUROAFROWPROEUROAFROAMROAMROAMROEUROAMROWP...,0,1,0,0
2020-01-06,AFALDZASADAOAIAGARAMAWAUATAZBSBHBDBBBYBEBZBJBM...,AfghanistanAlbaniaAlgeriaAmerican SamoaAndorra...,EMROEUROAFROWPROEUROAFROAMROAMROAMROEUROAMROWP...,3,4,0,0
2020-01-07,AFALDZASADAOAIAGARAMAWAUATAZBSBHBDBBBYBEBZBJBM...,AfghanistanAlbaniaAlgeriaAmerican SamoaAndorra...,EMROEUROAFROWPROEUROAFROAMROAMROAMROEUROAMROWP...,0,4,0,0
...,...,...,...,...,...,...,...
2021-05-24,AFALDZASADAOAIAGARAMAWAUATAZBSBHBDBBBYBEBZBJBM...,AfghanistanAlbaniaAlgeriaAmerican SamoaAndorra...,EMROEUROAFROWPROEUROAFROAMROAMROAMROEUROAMROWP...,533277,166587449,11008,3463135
2021-05-25,AFALDZASADAOAIAGARAMAWAUATAZBSBHBDBBBYBEBZBJBM...,AfghanistanAlbaniaAlgeriaAmerican SamoaAndorra...,EMROEUROAFROWPROEUROAFROAMROAMROAMROEUROAMROWP...,445688,167033137,9389,3472524
2021-05-26,AFALDZASADAOAIAGARAMAWAUATAZBSBHBDBBBYBEBZBJBM...,AfghanistanAlbaniaAlgeriaAmerican SamoaAndorra...,EMROEUROAFROWPROEUROAFROAMROAMROAMROEUROAMROWP...,468749,167501886,10695,3483219
2021-05-27,AFALDZASADAOAIAGARAMAWAUATAZBSBHBDBBBYBEBZBJBM...,AfghanistanAlbaniaAlgeriaAmerican SamoaAndorra...,EMROEUROAFROWPROEUROAFROAMROAMROAMROEUROAMROWP...,541229,168043115,11782,3495001
2021-05-28,AFASAIAGARAWAUBSBHBDBBBZBMBTBOXABRVGBNKHCAKYCL...,AfghanistanAmerican SamoaAnguillaAntigua and B...,EMROWPROAMROAMROAMROAMROWPROAMROEMROSEAROAMROA...,466521,110999615,10533,2274795

In [21]:
import plotly.express as px
import plotly.graph_objects as go

figure = go.Figure(data=[
    go.Scatter(name="New Cases",x=data.index,y=data["New_cases"]),
    go.Scatter(name="New Deaths",x=data.index,y=data["New_deaths"])
])
figure.write_html("covid_scatter2.html")

In [ ]:
datetime_series = df["DateReported"]
datetime_series[0].date().month

1

In [31]:
import datetime

datetime_series[0].strftime("%d/%m/%Y")

'03/01/2020'